/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "vcsec.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(VCSEC_AccelData, VCSEC_AccelData, AUTO)

PB_BIND(VCSEC_ActiveKey, VCSEC_ActiveKey, AUTO)

PB_BIND(VCSEC_Alert, VCSEC_Alert, AUTO)

PB_BIND(VCSEC_AlertHandlePulledWithoutAuth, VCSEC_AlertHandlePulledWithoutAuth, AUTO)

PB_BIND(VCSEC_AppDeviceInfo, VCSEC_AppDeviceInfo, AUTO)

PB_BIND(VCSEC_AuthenticationRequest, VCSEC_AuthenticationRequest, AUTO)

PB_BIND(VCSEC_AuthenticationRequestToken, VCSEC_AuthenticationRequestToken, AUTO)

PB_BIND(VCSEC_AuthenticationResponse, VCSEC_AuthenticationResponse, AUTO)

PB_BIND(VCSEC_BLEConfig, VCSEC_BLEConfig, AUTO)

PB_BIND(VCSEC_BLEConfigAll, VCSEC_BLEConfigAll, AUTO)

PB_BIND(VCSEC_BLEConfigCommand, VCSEC_BLEConfigCommand, AUTO)

PB_BIND(VCSEC_Capabilities, VCSEC_Capabilities, AUTO)

PB_BIND(VCSEC_ClosureMoveRequest, VCSEC_ClosureMoveRequest, AUTO)

PB_BIND(VCSEC_ClosureStatuses, VCSEC_ClosureStatuses, AUTO)

PB_BIND(VCSEC_CodeDescriptor, VCSEC_CodeDescriptor, AUTO)

PB_BIND(VCSEC_CommandStatus, VCSEC_CommandStatus, AUTO)

PB_BIND(VCSEC_ConnectionMetrics, VCSEC_ConnectionMetrics, AUTO)

PB_BIND(VCSEC_DelaySleepRequest, VCSEC_DelaySleepRequest, AUTO)

PB_BIND(VCSEC_DeviceMotion, VCSEC_DeviceMotion, AUTO)

PB_BIND(VCSEC_FromRCI, VCSEC_FromRCI, AUTO)

PB_BIND(VCSEC_FromVCSECMessage, VCSEC_FromVCSECMessage, AUTO)

PB_BIND(VCSEC_Genealogy, VCSEC_Genealogy, AUTO)

PB_BIND(VCSEC_GenealogyResponse, VCSEC_GenealogyResponse, AUTO)

PB_BIND(VCSEC_GetCodeDescriptor, VCSEC_GetCodeDescriptor, AUTO)

PB_BIND(VCSEC_GetReaderKey, VCSEC_GetReaderKey, AUTO)

PB_BIND(VCSEC_GetSessionInfoRequest, VCSEC_GetSessionInfoRequest, AUTO)

PB_BIND(VCSEC_HandlePulledWithoutAuthDeviceSpecificPayload, VCSEC_HandlePulledWithoutAuthDeviceSpecificPayload, AUTO)

PB_BIND(VCSEC_InformationRequest, VCSEC_InformationRequest, AUTO)

PB_BIND(VCSEC_KeyfobInfo, VCSEC_KeyfobInfo, AUTO)

PB_BIND(VCSEC_KeyIdentifier, VCSEC_KeyIdentifier, AUTO)

PB_BIND(VCSEC_KeyIdentity, VCSEC_KeyIdentity, AUTO)

PB_BIND(VCSEC_KeyMetadata, VCSEC_KeyMetadata, AUTO)

PB_BIND(VCSEC_KeyStatus, VCSEC_KeyStatus, AUTO)

PB_BIND(VCSEC_KeyStatusInfo, VCSEC_KeyStatusInfo, AUTO)

PB_BIND(VCSEC_MIConfigurationData, VCSEC_MIConfigurationData, AUTO)

PB_BIND(VCSEC_MISessionRequest, VCSEC_MISessionRequest, AUTO)

PB_BIND(VCSEC_MISessionResponse, VCSEC_MISessionResponse, AUTO)

PB_BIND(VCSEC_MISessionStop, VCSEC_MISessionStop, AUTO)

PB_BIND(VCSEC_MISessionStopped, VCSEC_MISessionStopped, AUTO)

PB_BIND(VCSEC_NFCSEState, VCSEC_NFCSEState, AUTO)

PB_BIND(VCSEC_NominalError, VCSEC_NominalError, AUTO)

PB_BIND(VCSEC_PermissionChange, VCSEC_PermissionChange, AUTO)

PB_BIND(VCSEC_PersonalizationInformation, VCSEC_PersonalizationInformation, AUTO)

PB_BIND(VCSEC_PublicKey, VCSEC_PublicKey, AUTO)

PB_BIND(VCSEC_RCISignature, VCSEC_RCISignature, AUTO)

PB_BIND(VCSEC_ReplaceKey, VCSEC_ReplaceKey, AUTO)

PB_BIND(VCSEC_ResetTrackerStats, VCSEC_ResetTrackerStats, AUTO)

PB_BIND(VCSEC_SessionInfo, VCSEC_SessionInfo, AUTO)

PB_BIND(VCSEC_SetTPConfigration, VCSEC_SetTPConfigration, AUTO)

PB_BIND(VCSEC_SetUpdaterLocation, VCSEC_SetUpdaterLocation, AUTO)

PB_BIND(VCSEC_Signatures, VCSEC_Signatures, AUTO)

PB_BIND(VCSEC_Signatures_SessionInfo, VCSEC_Signatures_SessionInfo, AUTO)

PB_BIND(VCSEC_SignedMessage, VCSEC_SignedMessage, AUTO)

PB_BIND(VCSEC_SignedMessage_status, VCSEC_SignedMessage_status, AUTO)

PB_BIND(VCSEC_SleepManagerRequest, VCSEC_SleepManagerRequest, AUTO)

PB_BIND(VCSEC_SleepManagerStats, VCSEC_SleepManagerStats, AUTO)

PB_BIND(VCSEC_StageBlock, VCSEC_StageBlock, AUTO)

PB_BIND(VCSEC_ToRCI, VCSEC_ToRCI, AUTO)

PB_BIND(VCSEC_ToVCSECMessage, VCSEC_ToVCSECMessage, AUTO)

PB_BIND(VCSEC_TPAdv, VCSEC_TPAdv, AUTO)

PB_BIND(VCSEC_TPData, VCSEC_TPData, AUTO)

PB_BIND(VCSEC_TPLRDetection, VCSEC_TPLRDetection, AUTO)

PB_BIND(VCSEC_TPMotionConfig, VCSEC_TPMotionConfig, AUTO)

PB_BIND(VCSEC_TPMSAlarms, VCSEC_TPMSAlarms, AUTO)

PB_BIND(VCSEC_TPNewSensorData, VCSEC_TPNewSensorData, AUTO)

PB_BIND(VCSEC_TPNotifyTrackerStats, VCSEC_TPNotifyTrackerStats, AUTO)

PB_BIND(VCSEC_TPStationaryConfig, VCSEC_TPStationaryConfig, AUTO)

PB_BIND(VCSEC_TPWheelUnitInfo, VCSEC_TPWheelUnitInfo, AUTO)

PB_BIND(VCSEC_UnknownKeyInfo, VCSEC_UnknownKeyInfo, AUTO)

PB_BIND(VCSEC_UnsecureNotification, VCSEC_UnsecureNotification, AUTO)

PB_BIND(VCSEC_UnsignedMessage, VCSEC_UnsignedMessage, AUTO)

PB_BIND(VCSEC_UpdaterCommand, VCSEC_UpdaterCommand, AUTO)

PB_BIND(VCSEC_UpdaterResponse, VCSEC_UpdaterResponse, AUTO)

PB_BIND(VCSEC_UpdaterStatus, VCSEC_UpdaterStatus, AUTO)

PB_BIND(VCSEC_VehicleInfo, VCSEC_VehicleInfo, AUTO)

PB_BIND(VCSEC_VehicleStatus, VCSEC_VehicleStatus, AUTO)

PB_BIND(VCSEC_VerifyAndInstallApp, VCSEC_VerifyAndInstallApp, AUTO)

PB_BIND(VCSEC_WhitelistEntryInfo, VCSEC_WhitelistEntryInfo, AUTO)

PB_BIND(VCSEC_WhitelistInfo, VCSEC_WhitelistInfo, AUTO)

PB_BIND(VCSEC_WhitelistOperation, VCSEC_WhitelistOperation, AUTO)

PB_BIND(VCSEC_WhitelistOperation_status, VCSEC_WhitelistOperation_status, AUTO)






















































