name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: tesla-ble-version
    attributes:
      label: Tesla BLE Version
    validations:
      required: true
  - type: input
    id: esphome-version
    attributes:
      label: ESPHome Version
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant logs. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details
      description: Anything else we need to know?
