external_components:
  - components: [ tesla_ble_vehicle ]
    # uncomment for local dev
    # source: components
    source: github://yoziru/esphome-tesla-ble/components@main

ble_client:
  - mac_address: !secret ble_mac_address
    id: ble_tesla_id

tesla_ble_vehicle:
  ble_client_id: ble_tesla_id
  id: tesla_ble_vehicle_id
  vin: !secret tesla_vin
  update_interval: 1min # default
  is_asleep:
    name: "Asleep"
  is_user_present:
    name: "User presence"
  is_unlocked:
    name: "Doors"

button:
  - platform: restart
    name: Restart
    icon: mdi:restart
    entity_category: diagnostic

  - platform: template
    id: ble_pair
    name: Pair BLE key
    icon: mdi:key-wireless
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->startPair();

  - platform: template
    name: Wake up
    icon: mdi:sleep-off
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->wakeVehicle();

  - platform: template
    name: Regenerate key
    icon: mdi:key-change
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->regenerateKey();
    entity_category: diagnostic
    disabled_by_default: true

  - platform: template
    name: Force data update
    icon: mdi:database-sync
    on_press:
      - lambda: id(tesla_ble_vehicle_id)->sendInfoStatus();
    entity_category: diagnostic

sensor:
  - platform: ble_client
    type: rssi
    ble_client_id: ble_tesla_id
    name: "BLE Signal"
    icon: mdi:bluetooth
    update_interval: 60s

switch:
  - platform: template
    name: "Charger switch"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    turn_on_action:
      - lambda: id(tesla_ble_vehicle_id)->setChargingSwitch(true);
    turn_off_action:
      - lambda: id(tesla_ble_vehicle_id)->setChargingSwitch(false);

  - platform: ble_client
    ble_client_id: ble_tesla_id
    name: "BLE Connection"
    entity_category: diagnostic

number:
  - platform: template
    name: "Charging amps"
    id: charging_amps
    icon: mdi:ev-station
    mode: slider
    min_value: 0
    max_value: 32
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - lambda: |-
            int var_x = static_cast<int>(x);
            id(tesla_ble_vehicle_id)->setChargingAmps(var_x);
  - platform: template
    name: "Charging limit"
    id: charging_limit
    icon: mdi:ev-station
    mode: slider
    min_value: 50
    max_value: 100
    step: 1
    optimistic: true
    restore_value: true
    on_value:
      then:
        - lambda: |-
            int var_x = static_cast<int>(x);
            id(tesla_ble_vehicle_id)->setChargingLimit(var_x);
