name: CI

on:
  pull_request:

jobs:
  ci:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file:
          - tesla-ble-esp32-generic.yml
          - tesla-ble-m5stack-atoms3.yml
          - tesla-ble-m5stack-nanoc6.yml
    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3
      - name: Mock secrets.yaml from example
        run: cp secrets.yaml.example secrets.yaml
      - name: Get ESPHome version
        id: get_esphome_version
        # read esphome version from requirements.txt
        run: |
          esphome_version=$(grep esphome requirements.txt | cut -d'=' -f3)
          echo "esphome_version=$esphome_version" >> "$GITHUB_OUTPUT"
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@4ef4722a2935eac47b7e227fe0e1f8e0f8afcc42 # v7.3.0
        with:
          yaml-file: ${{ matrix.file }}
          version: ${{ steps.get_esphome_version.outputs.esphome_version }}
